### ISSUE TITLE
hello 捐款开个支付宝帐户吧

### ISSUE THREAD

**Issue by haha1903** [bd-hello/dist#1]
让我们这些没有 btc 帐户的人，也能支持你一下。

**Comment by neuloner** [comment]
强低。

On Sun, May 4, 2014 at 1:32 PM, haha1903 notifications@github.com wrote:

> 让我们这些没有 btc 帐户的人，也能支持你一下。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bd-hello/dist/issues/1
> .

## 

Best regards,

Jiandong         loner
——————————————————
Don't let the living erode our individuality.
不要让生活磨灭了我们的个性

**Comment by bd-hello** [comment]
你们懂的，我不能这样贴支付宝账号啊。支付宝账号是有的，可以私下询问，谢谢支持啦！
